#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_DIALOG1                             100
#define IDI_ICON1                               101
#define IDR_MENU1                               102
#define IDSET                                   1000
#define IDC_SPC_EQ_LEFT                         1001
#define IDC_SHRT_EQ                             1002
#define IDC_SPC_EQ                              1003
#define IDC_MERC_NAME                           1004
#define IDC_VEST_EQ                             1005
#define IDC_AMMO_EQ                             1006
#define IDC_COMBO2                              1007
#define IDC_COMBO3                              1008
#define IDC_ADDRESS                             1009
#define IDC_LEV                                 1010
#define IDC_TP                                  1011
#define IDC_AG                                  1012
#define IDC_EX                                  1013
#define IDC_INV_ITEM_ID                         1015
#define IDC_HELM_EQ                             1016
#define IDC_WPN_INV                             1018
#define IDC_WPN_EQ                              1024
#define IDC_HELM_EQ_DUR                         1026
#define IDC_WPN_EQ_DUR                          1028
#define IDC_DEX                                 1030
#define IDC_STR                                 1032
#define IDC_INT                                 1034
#define IDC_PER                                 1036
#define IDC_SHRT_EQ_DUR                         1038
#define IDC_VEST_DUR                            1040
#define IDC_SHOES_EQ                            1042
#define IDC_SHOES_DUR                           1044
#define IDC_PANTS_EQ                            1046
#define IDC_PANTS_DUR                           1048
#define IDC_AMMO_EQ_CNT                         1050
#define IDC_WPN_MOD                             1052
#define IDC_MED                                 1058
#define IDC_EXPL                                1059
#define IDC_MARK                                1060
#define IDC_STEALTH                             1061
#define IDC_MECH                                1062
#define IDC_HLTH                                1066
#define IDC_STAMINA                             1067
#define IDC_MORAL                               1068
#define IDC_EYE_EQ                              1074
#define IDC_EYE_EQ_DUR                          1075
#define IDC_MED_COND                            1077
#define IDC_MERC_FAC                            1078
#define IDC_COMBO1                              1079
#define IDC_WPN_INV_DUR                         40000
#define IDC_AMMO_INV_CNT                        40002
#define IDM_DUMP_CHARACTER                      50000
