#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_DIALOG1                             100
#define IDI_ICON1                               101
#define IDR_MENU1                               102
#define IDSET                                   1000
#define IDC_SPC_EQ_LEFT                         1001
#define IDC_MERC_NAME                           1004
#define IDC_ADDRESS                             1009
#define IDC_LEV                                 1010
#define IDC_TP                                  1011
#define IDC_AG                                  1012
#define IDC_EX                                  1013
#define IDC_BLEED_RATE                          1014
#define IDC_INV_ITEM_ID                         1015
#define IDC_HELM_EQ_DUR                         1026
#define IDC_WPN_EQ_DUR                          1028
#define IDC_DEX                                 1030
#define IDC_STR                                 1032
#define IDC_INT                                 1034
#define IDC_PER                                 1036
#define IDC_SHRT_EQ_DUR                         1038
#define IDC_VEST_DUR                            1040
#define IDC_SHOES_DUR                           1044
#define IDC_PANTS_DUR                           1048
#define IDC_AMMO_EQ_CNT                         1050
#define IDC_MED                                 1058
#define IDC_EXPL                                1059
#define IDC_MARK                                1060
#define IDC_STEALTH                             1061
#define IDC_MECH                                1062
#define IDC_HLTH                                1066
#define IDC_STAMINA                             1067
#define IDC_EYE_EQ_DUR                          1075
#define IDC_MED_COND                            1077
#define IDC_MERC_FAC                            1078
#define IDC_COMBO_CHARACTER                     1079
#define IDC_AMMO_INV_CNT                        1090
#define IDC_WPN_INV_DUR                         1091
#define IDM_EQUIPMENT1                          30000
#define IDM_HEAL_CHARACTER                      30001
#define IDM_KILL_CHARACTER                      30002
#define IDM_STUN_CHARACTER                      30003
#define IDM_DUMP_CHARACTER                      30004
#define IDM_DUMP_ALL                            30005
#define IDC_COMBO_EQUIPED_WEAPON                40000
#define IDM_CHARACTER_LIFE_STATS                40000
#define IDC_COMBO_INVENTORY_WEAPON              40001
#define IDC_COMBO_INVENTORY_SLOT                40002
#define IDC_COMBO_WEAPON_SLOT                   40003
#define IDC_MONEY                               40004
#define IDC_COMBO_WEAPON_MOD                    40005
#define IDC_COMBO_HELMET                        40006
#define IDC_COMBO_VEST                          40007
#define IDC_COMBO_SHIRT                         40008
#define IDC_COMBO_PANTS                         40009
#define IDC_COMBO_SHOES                         40010
#define IDC_COMBO_EYEWEAR                       40011
#define IDC_COMBO_AMMO                          40012
#define IDC_COMBO_SPECIAL                       40013
#define IDHEAL_CHARACTER                        40014
#define IDSUPER                                 40015
#define IDFIXGEAR                               40016
#define IDMASTERKEY                             40017
#define IDC_DAYS_SERVICE                        40018
#define IDC_MELEE_ATTACKS                       40019
#define IDC_GRENADES_THROWN                     40020
#define IDC_ROCKETS_FIRED                       40021
#define IDC_BULLETS_SHOT                        40022
#define IDC_ENEMIES_KILLED                      40023
#define IDC_TOTAL_DAMAGE_DEALT                  40024
#define IDC_TOTAL_DAMAGE_TAKEN                  40025
#define IDC_TIMES_BLEEDING                      40026
#define IDC_TIMES_WOUNDED                       40027
#define IDC_TIMES_RESCUED                       40028
#define IDC_UNSUCCESSFUL_HEALING_CHECKS         40029
#define IDC_TOTAL_AMOUNT_HEALTH_RESTORED        40031
#define IDC_SUCCESSFUL_HEALING_CHECKS           40032
#define IDC_COMBO_TRAIT_NUMBER                  40033
#define IDC_COMBO_TRAIT_DESC                    40034
