
<Structures>
  <Structure Name="JABIA_Character_config" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="0" Vartype="4 Bytes" Bytesize="4" Description="Agility" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="4" Vartype="4 Bytes" Bytesize="4" Description="Dexterity" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="8" Vartype="4 Bytes" Bytesize="4" Description="Strength" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="12" Vartype="4 Bytes" Bytesize="4" Description="Wisdom" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="16" Vartype="4 Bytes" Bytesize="4" Description="Perception" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="20" Vartype="4 Bytes" Bytesize="4" Description="Medical" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="24" Vartype="4 Bytes" Bytesize="4" Description="Explosives" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="28" Vartype="4 Bytes" Bytesize="4" Description="Marksmanship" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="32" Vartype="4 Bytes" Bytesize="4" Description="Sneak" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="36" Vartype="4 Bytes" Bytesize="4" Description="Mechanics" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="40" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="44" Vartype="4 Bytes" Bytesize="4" Description="TotcalCost" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="48" Vartype="4 Bytes" Bytesize="4" Description="EquipmentCost" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="52" Vartype="4 Bytes" Bytesize="4" Description="HiringFee" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="56" Vartype="4 Bytes" Bytesize="4" Description="HiringDeathRate" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="60" Vartype="4 Bytes" Bytesize="4" Description="HiringReputation" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="64" Vartype="4 Bytes" Bytesize="4" Description="VoiceType" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="68" Vartype="4 Bytes" Bytesize="4" Description="Portrait" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="72" Vartype="4 Bytes" Bytesize="4" Description="FacialAnimType" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="76" Vartype="4 Bytes" Bytesize="4" Description="TextIndex" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="80" Vartype="4 Bytes" Bytesize="4" Description="EyeColor" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="84" Vartype="4 Bytes" Bytesize="4" Description="RejectAnswer" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="88" Vartype="4 Bytes" Bytesize="4" Description="Cap" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="92" Vartype="4 Bytes" Bytesize="4" Description="Head" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="96" Vartype="4 Bytes" Bytesize="4" Description="Glasses" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="100" Vartype="4 Bytes" Bytesize="4" Description="Torso" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="104" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="108" Vartype="4 Bytes" Bytesize="4" Description="Legs" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="112" Vartype="4 Bytes" Bytesize="4" Description="Feet" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="116" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="120" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="124" Vartype="4 Bytes" Bytesize="4" Description="XPForKilling" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="128" Vartype="4 Bytes" Bytesize="4" Description="Level" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="132" Vartype="4 Bytes" Bytesize="4" Description="UnlockTrader" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="136" Vartype="4 Bytes" Bytesize="4" Description="TraderMoney" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="140" Vartype="4 Bytes" Bytesize="4" Description="RecruitAchievement" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="144" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="148" Vartype="String" Bytesize="16" Description="Nickname" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="164" Vartype="4 Bytes" Bytesize="4" Description="NameLength" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="168" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="172" Vartype="4 Bytes" Bytesize="4" Description="NPCType" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="176" Vartype="4 Bytes" Bytesize="4" Description="Sex" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="180" Vartype="4 Bytes" Bytesize="4" Description="SkinColor" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="184" Vartype="4 Bytes" Bytesize="4" Description="Faction" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="188" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="192" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="196" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="200" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="204" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="208" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="212" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="216" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="220" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="224" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="228" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="232" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="236" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="240" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="244" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="248" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="252" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="256" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="260" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="264" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="268" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="272" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="276" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="280" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="284" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="288" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="292" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="296" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="300" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="304" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="308" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="312" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="316" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="320" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="324" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="328" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="332" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="336" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="340" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="344" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="348" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="352" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="356" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="360" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="364" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="368" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="372" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="376" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="380" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="384" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="388" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="392" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="396" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="400" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="404" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="408" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="412" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="416" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="420" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="424" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="428" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="432" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="436" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="440" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="444" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="448" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="452" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="456" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="460" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="464" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="468" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="472" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
      <Element Offset="476" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Hexadecimal" BackgroundColor="80000005"/>
    </Elements>
  </Structure>
</Structures>